[pytest]
filterwarnings =
    ignore:CSR support in pyOpenSSL is deprecated:DeprecationWarning:josepy\.
    ignore:CSR support in pyOpenSSL is deprecated:DeprecationWarning:acme\.
    ignore:X509Extension support in pyOpenSSL is deprecated:DeprecationWarning:acme\.
    ignore:Inheritance class HomeAssistantApplication from web.Application is discouraged:DeprecationWarning:homeassistant\.

